[package]
name = "cli-app"
version = "0.1.0"
authors = ["etrnal70 <etrnal70@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
box_drawing = "0.1.2"
